



"""Intrusion is when an attacker gets unauthorized access to a device, network, or system. Cyber
criminals use advanced techniques to sneak into organizations without being detected.
IDS observes network traffic for malicious transactions and sends immediate alerts when it is
observed. It is software that checks a network or system for malicious activities or policy
violations. Each illegal activity or violation is often recorded either centrally using an SIEM
system or notified to an administration. IDS monitors a network or system for malicious
activity and protects a computer network from unauthorized access from users, including
perhaps insiders. The intrusion detector learning task is to build a predictive model (i.e. a
classifier) capable of distinguishing between ‘bad connections’ and ‘good connections’.
Common Methods of Intrusion
• Address Spoofing: Hiding the source of an attack by using fake or unsecured proxy
servers making it hard to identify the attacker.
• Fragmentation: Sending data in small pieces to slip past detection systems.
• Pattern Evasion: Changing attack methods to avoid detection by IDS systems.
• Coordinated Attack: Using multiple attackers or ports to scan a network, confusing
the IDS and making it hard to see what is happening.
Intrusion Detection System Evasion Techniques
• Fragmentation: Dividing the packet into smaller packet called fragment This makes
it impossible to identify an intrusion because there can't be a malware signature.
• Packet Encoding: Encoding packets using methods like Base64 or hexadecimal.
• Traffic Obfuscation: By making message more complicated to interpret.
• Encryption: Several security features such as data integrity, confidentiality, and data
privacy, are provided by encryption.
Working of Intrusion Detection System(IDS)
• An IDS (Intrusion Detection System) monitors the traffic on a computer network to
detect any suspicious activity.
• It analyzes the data flowing through the network to look for patterns and signs of
abnormal behavior.
• The IDS compares the network activity to a set of predefined rules and patterns to
identify any activity that might indicate an attack or intrusion.
• If the IDS detects something that matches one of these rules or patterns, it sends an
alert to the system administrator.
Roll No:160122733173 Week-12 Date:23/10/2025
Page No. Signature of the Faculty………………………...
• The system administrator can then investigate the alert and take action to prevent any
damage or further intrusion"""





"""
. Update the system --> sudo apt update
2. Install Snort and required tools
sudo apt install -y snort python3 python3-pip netcat nmap
Installs:
• Snort → Network intrusion detection system
• Python3 & pip3 → Needed for Python scripts or traffic generation
• Netcat → For network testing
• Nmap → For network scanning
• Additional packages installed automatically: libdaq2, libdumbnet1, liblinear4,
libluajit-5.1-2, lua-lpeg, snort-rules-default, oinkmaster.
3. Install Scapy (Python packet generator) --> sudo pip3 install scapy
Configuration:
1. Create necessary directories
sudo mkdir -p /etc/snort/rules /var/log/snort
• /etc/snort/rules → Store custom rules for Snort.
• /var/log/snort → Store logs generated by Snort.
• -p ensures parent directories are created if not existing.
2: Change ownership of directories
sudo chown -R $USER:$USER /etc/snort /var/log/snort
• Ensures the current user has read/write permissions for Snort directories.
• -R → Recursively change ownership of directories and their contents.
3: Configure network variables
var HOME_NET 127.0.0.1
• HOME_NET → Defines your local network IP that Snort will monitor.
• Here we use 127.0.0.1 (localhost) for testing.
• In real scenarios, this will be your LAN IP range, e.g., 192.168.1.0/24.
4. Write a sample Snort rule
File: /etc/snort/rules/local.rules
nano /etc/snort/rules/local.rules
Example rule inside file:
alert icmp any any -> $HOME_NET any (msg:"ICMP packet detected"; sid:1000001; rev:1;)
• alert → Action Snort will take (here, alert).
• icmp any any -> $HOME_NET any → Detects any ICMP traffic coming to your host.
• msg → Message displayed in log.
• Sid , rev → Unique Snort ID for the rule, Rule revision number.
5. Update Snort configuration
File: /etc/snort/snort.conf
Add your local rules:
include $RULE_PATH/local.rules (Ensures Snort reads your custom rules)
6. Run Snort in IDS mode
sudo snort -A console -q -c /etc/snort/snort.conf -i lo
• -A console → Show alerts in the terminal.
• -q → Quiet mode (reduces verbose messages).
• -c /etc/snort/snort.conf → Use your configuration file.
• -i lo → Monitor the loopback interface (localhost).
• For real networks, replace lo with eth0 or wlan0.
7. Terminal 2 – Generate Network Traffic
Send ICMP packets (ping) to localhost --> ping 127.0.0.1
This generates ICMP packets that Snort should detect.
• Observation in Terminal 1 --> [**] [1:1000001:1] ICMP packet detected [**]
8. Terminal 1 – Check Log File
View Snort log file --> cat /var/log/snort/alert
Each entry shows your alert message "ICMP packet detected"."""

